use std::collections::HashMap;
use once_cell::sync::Lazy;

pub enum GoalType {
    Normal,
    Medal,
    GoldMedal,  // makes tracking golds a bit easier
    Pro,    // encompasses pro goals and competition platinums
}

// constructs a hash table of every goal in the game to translate from a name to a position in our own career table
pub static GOAL_TABLE: Lazy<HashMap<&str, (u32, u32, u32, GoalType)>> = Lazy::new(|| {
    let mut table: HashMap<&str, (u32, u32, u32, GoalType)> = HashMap::new();

    for (k, v) in GOAL_LIST {
        table.insert(k, v);
    }

    table
});

// list of all goals, in the format (name, (tour, level, index)) 
// includes all games because i suspect they might merge them someday
const GOAL_LIST: [(&str, (u32, u32, u32, GoalType)); 399] = [
    // THPS1
    ("/Game/Environments/THPS1/Warehouse/Goals/Data/warehouse_score_high.warehouse_score_high", (0, 0, 0, GoalType::Normal)),
    ("/Game/Environments/THPS1/Warehouse/Goals/Data/warehouse_score_pro.warehouse_score_pro", (0, 0, 1, GoalType::Normal)),
    ("/Game/Environments/THPS1/Warehouse/Goals/Data/warehouse_score_sick.warehouse_score_sick", (0, 0, 2, GoalType::Normal)),
    ("/Game/Environments/THPS1/Warehouse/Goals/Data/warehouse_score_combo.warehouse_score_combo", (0, 0, 3, GoalType::Normal)),
    ("/Game/Environments/THPS1/Warehouse/Goals/Data/warehouse_collect_SKATE.warehouse_collect_SKATE", (0, 0, 4, GoalType::Normal)),
    ("/Game/Environments/THPS1/Warehouse/Goals/Data/warehouse_collect_5_items.warehouse_collect_5_items", (0, 0, 5, GoalType::Normal)),
    ("/Game/Environments/THPS1/Warehouse/Goals/Data/warehouse_env_5_boxes.warehouse_env_5_boxes", (0, 0, 6, GoalType::Normal)),
    ("/Game/Environments/THPS1/Warehouse/Goals/Data/warehouse_BigRail.warehouse_BigRail", (0, 0, 7, GoalType::Normal)),
    ("/Game/Environments/THPS1/Warehouse/Goals/Data/warehouse_ChannelGap.warehouse_ChannelGap", (0, 0, 8, GoalType::Normal)),
    ("/Game/Environments/THPS1/Warehouse/Goals/Data/warehouse_collect_secret_tape.warehouse_collect_secret_tape", (0, 0, 9, GoalType::Normal)),

    ("/Game/Environments/THPS1/School/Goals/Data/school_score_high.school_score_high", (0, 1, 0, GoalType::Normal)),
    ("/Game/Environments/THPS1/School/Goals/Data/school_score_pro.school_score_pro", (0, 1, 1, GoalType::Normal)),
    ("/Game/Environments/THPS1/School/Goals/Data/school_score_sick.school_score_sick", (0, 1, 2, GoalType::Normal)),
    ("/Game/Environments/THPS1/School/Goals/Data/school_score_combo.school_score_combo", (0, 1, 3, GoalType::Normal)),
    ("/Game/Environments/THPS1/School/Goals/Data/school_collect_SKATE.school_collect_SKATE", (0, 1, 4, GoalType::Normal)),
    ("/Game/Environments/THPS1/School/Goals/Data/school_collect_5_items.school_collect_5_items", (0, 1, 5, GoalType::Normal)),
    ("/Game/Environments/THPS1/School/Goals/Data/school_grind_tables.school_grind_tables", (0, 1, 6, GoalType::Normal)),
    ("/Game/Environments/THPS1/School/Goals/Data/school_wallride_beells.school_wallride_beells", (0, 1, 7, GoalType::Normal)),
    ("/Game/Environments/THPS1/School/Goals/Data/school_heelflip_kicker.school_heelflip_kicker", (0, 1, 8, GoalType::Normal)),
    ("/Game/Environments/THPS1/School/Goals/Data/school_collect_secret_tape.school_collect_secret_tape", (0, 1, 9, GoalType::Normal)),

    ("/Game/Environments/THPS1/Mall/Goals/Data/Mall_score_high.Mall_score_high", (0, 2, 0, GoalType::Normal)),
    ("/Game/Environments/THPS1/Mall/Goals/Data/Mall_score_pro.Mall_score_pro", (0, 2, 1, GoalType::Normal)),
    ("/Game/Environments/THPS1/Mall/Goals/Data/Mall_score_sick.Mall_score_sick", (0, 2, 2, GoalType::Normal)),
    ("/Game/Environments/THPS1/Mall/Goals/Data/Mall_score_combo.Mall_score_combo", (0, 2, 3, GoalType::Normal)),
    ("/Game/Environments/THPS1/Mall/Goals/Data/Mall_collect_SKATE.Mall_collect_SKATE", (0, 2, 4, GoalType::Normal)),
    ("/Game/Environments/THPS1/Mall/Goals/Data/Mall_collect_5_items.Mall_collect_5_items", (0, 2, 5, GoalType::Normal)),
    ("/Game/Environments/THPS1/Mall/Goals/Data/Mall_env_directories.Mall_env_directories", (0, 2, 6, GoalType::Normal)),
    ("/Game/Environments/THPS1/Mall/Goals/Data/Mall_gap_Slide_CoffeeGrind.Mall_gap_Slide_CoffeeGrind", (0, 2, 7, GoalType::Normal)),
    ("/Game/Environments/THPS1/Mall/Goals/Data/Mall_gap_AirWalk_FlylingLeap.Mall_gap_AirWalk_FlylingLeap", (0, 2, 8, GoalType::Normal)),
    ("/Game/Environments/THPS1/Mall/Goals/Data/Mall_collect_secret_tape.Mall_collect_secret_tape", (0, 2, 9, GoalType::Normal)),

    ("/Game/Environments/THPS1/Skate/Goals/Data/skate_medal_bronze.skate_medal_bronze", (0, 3, 0, GoalType::Medal)),
    ("/Game/Environments/THPS1/Skate/Goals/Data/skate_medal_silver.skate_medal_silver", (0, 3, 1, GoalType::Medal)),
    ("/Game/Environments/THPS1/Skate/Goals/Data/skate_medal_gold.skate_medal_gold", (0, 3, 2, GoalType::GoldMedal)),

    ("/Game/Environments/THPS1/Downtown/Goals/Data/Downtown_score_high.Downtown_score_high", (0, 4, 0, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downtown/Goals/Data/Downtown_score_pro.Downtown_score_pro", (0, 4, 1, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downtown/Goals/Data/Downtown_score_sick.Downtown_score_sick", (0, 4, 2, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downtown/Goals/Data/Downtown_score_combo.Downtown_score_combo", (0, 4, 3, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downtown/Goals/Data/Downtown_collect_SKATE.Downtown_collect_SKATE", (0, 4, 4, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downtown/Goals/Data/Downtown_collect_5_items.Downtown_collect_5_items", (0, 4, 5, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downtown/Goals/Data/Downtown_collect_NoSkate.Downtown_collect_NoSkate", (0, 4, 6, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downtown/Goals/Data/Downtown_collect_secret_tape.Downtown_collect_secret_tape", (0, 4, 7, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downtown/Goals/Data/Downtown_roofgap_goal.Downtown_roofgap_goal", (0, 4, 8, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downtown/Goals/Data/Downtown_car_goal.Downtown_car_goal", (0, 4, 9, GoalType::Normal)),

    ("/Game/Environments/THPS1/Downhill/Goals/Data/Downhill_score_high.Downhill_score_high", (0, 5, 0, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downhill/Goals/Data/Downhill_score_pro.Downhill_score_pro", (0, 5, 1, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downhill/Goals/Data/Downhill_score_sick.Downhill_score_sick", (0, 5, 2, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downhill/Goals/Data/Downhill_score_combo.Downhill_score_combo", (0, 5, 3, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downhill/Goals/Data/Downhill_Collect_env.Downhill_Collect_env", (0, 5, 4, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downhill/Goals/Data/Downhill_collect_SKATE.Downhill_collect_SKATE", (0, 5, 5, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downhill/Goals/Data/Donwhill_Collect_5_Items.Donwhill_Collect_5_Items", (0, 5, 6, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downhill/Goals/Data/Downhill_collect_secret_tape.Downhill_collect_secret_tape", (0, 5, 7, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downhill/Goals/Data/Donwhill_Gap_HazardGap.Donwhill_Gap_HazardGap", (0, 5, 8, GoalType::Normal)),
    ("/Game/Environments/THPS1/Downhill/Goals/Data/Donwhill_Gaps_Hydrophobic.Donwhill_Gaps_Hydrophobic", (0, 5, 9, GoalType::Normal)),

    ("/Game/Environments/THPS1/Burnside/Goals/Data/burnside_medal_bronze.burnside_medal_bronze", (0, 6, 0, GoalType::Medal)),
    ("/Game/Environments/THPS1/Burnside/Goals/Data/burnside_medal_silver.burnside_medal_silver", (0, 6, 1, GoalType::Medal)),
    ("/Game/Environments/THPS1/Burnside/Goals/Data/burnside_medal_gold.burnside_medal_gold", (0, 6, 2, GoalType::GoldMedal)),

    ("/Game/Environments/THPS1/Streets/Goals/Data/streets_score_high.streets_score_high", (0, 7, 0, GoalType::Normal)),
    ("/Game/Environments/THPS1/Streets/Goals/Data/streets_score_pro.streets_score_pro", (0, 7, 1, GoalType::Normal)),
    ("/Game/Environments/THPS1/Streets/Goals/Data/streets_score_sick.streets_score_sick", (0, 7, 2, GoalType::Normal)),
    ("/Game/Environments/THPS1/Streets/Goals/Data/streets_score_combo.streets_score_combo", (0, 7, 3, GoalType::Normal)),
    ("/Game/Environments/THPS1/Streets/Goals/Data/streets_wreck_cars.streets_wreck_cars", (0, 7, 4, GoalType::Normal)),
    ("/Game/Environments/THPS1/Streets/Goals/Data/streets_collect_SKATE.streets_collect_SKATE", (0, 7, 5, GoalType::Normal)),
    ("/Game/Environments/THPS1/Streets/Goals/Data/streets_collect_5_items.streets_collect_5_items", (0, 7, 6, GoalType::Normal)),
    ("/Game/Environments/THPS1/Streets/Goals/Data/streets_gap_hubba.streets_gap_hubba", (0, 7, 7, GoalType::Normal)),
    ("/Game/Environments/THPS1/Streets/Goals/Data/streets_gap_fountain.streets_gap_fountain", (0, 7, 8, GoalType::Normal)),
    ("/Game/Environments/THPS1/Streets/Goals/Data/streets_collect_secret_tape.streets_collect_secret_tape", (0, 7, 9, GoalType::Normal)),

    ("/Game/Environments/THPS1/Roswell/Goals/Data/Roswell_Medal_Bronze.roswell_medal_bronze", (0, 8, 0, GoalType::Medal)),
    ("/Game/Environments/THPS1/Roswell/Goals/Data/roswell_medal_silver.roswell_medal_silver", (0, 8, 1, GoalType::Medal)),
    ("/Game/Environments/THPS1/Roswell/Goals/Data/roswell_medal_gold.roswell_medal_gold", (0, 8, 2, GoalType::GoldMedal)),

    // THPS2
    ("/Game/Environments/THPS2/Hangar/Goals/Data/hanger_score_high.hanger_score_high", (1, 0, 0, GoalType::Normal)),
    ("/Game/Environments/THPS2/Hangar/Goals/Data/hanger_score_pro.hanger_score_pro", (1, 0, 1, GoalType::Normal)),
    ("/Game/Environments/THPS2/Hangar/Goals/Data/hanger_score_sick.hanger_score_sick", (1, 0, 2, GoalType::Normal)),
    ("/Game/Environments/THPS2/Hangar/Goals/Data/hanger_score_combo.hanger_score_combo", (1, 0, 3, GoalType::Normal)),
    ("/Game/Environments/THPS2/Hangar/Goals/Data/hanger_collect_SKATE.hanger_collect_SKATE", (1, 0, 4, GoalType::Normal)),
    ("/Game/Environments/THPS2/Hangar/Goals/Data/hanger_collect_5_items.hanger_collect_5_items", (1, 0, 5, GoalType::Normal)),
    ("/Game/Environments/THPS2/Hangar/Goals/Data/hanger_env_barrels.hanger_env_barrels", (1, 0, 6, GoalType::Normal)),
    ("/Game/Environments/THPS2/Hangar/Goals/Data/hanger_gap_hangtime.hanger_gap_hangtime", (1, 0, 7, GoalType::Normal)),
    ("/Game/Environments/THPS2/Hangar/Goals/Data/hanger_gap_nosegrind.hanger_gap_nosegrind", (1, 0, 8, GoalType::Normal)),
    ("/Game/Environments/THPS2/Hangar/Goals/Data/hanger_collect_secret_tape.hanger_collect_secret_tape", (1, 0, 9, GoalType::Normal)),

    ("/Game/Environments/THPS2/School2/Goals/Data/school2_score_high.school2_score_high", (1, 1, 0, GoalType::Normal)),
    ("/Game/Environments/THPS2/School2/Goals/Data/school2_score_pro.school2_score_pro", (1, 1, 1, GoalType::Normal)),
    ("/Game/Environments/THPS2/School2/Goals/Data/school2_score_sick.school2_score_sick", (1, 1, 2, GoalType::Normal)),
    ("/Game/Environments/THPS2/School2/Goals/Data/school2_score_combo.school2_score_combo", (1, 1, 3, GoalType::Normal)),
    ("/Game/Environments/THPS2/School2/Goals/Data/school2_collect_SKATE.school2_collect_SKATE", (1, 1, 4, GoalType::Normal)),
    ("/Game/Environments/THPS2/School2/Goals/Data/school2_collect_5_items.school2_collect_5_items", (1, 1, 5, GoalType::Normal)),
    ("/Game/Environments/THPS2/School2/Goals/Data/school2_gap_rails.school2_gap_rails", (1, 1, 6, GoalType::Normal)),
    ("/Game/Environments/THPS2/School2/Goals/Data/school2_gap_kickflip.school2_gap_kickflip", (1, 1, 7, GoalType::Normal)),
    ("/Game/Environments/THPS2/School2/Goals/Data/school2_collect_secret_tape.school2_collect_secret_tape", (1, 1, 8, GoalType::Normal)),
    ("/Game/Environments/THPS2/School2/Goals/Data/school2_wallride_bells.school2_wallride_bells", (1, 1, 9, GoalType::Normal)),

    ("/Game/Environments/THPS2/Marseille/Goals/Gaps/marseille_medal_bronze.marseille_medal_bronze", (1, 2, 0, GoalType::Medal)),
    ("/Game/Environments/THPS2/Marseille/Goals/Gaps/marseille_medal_silver.marseille_medal_silver", (1, 2, 1, GoalType::Medal)),
    ("/Game/Environments/THPS2/Marseille/Goals/Gaps/marseille_medal_gold.marseille_medal_gold", (1, 2, 2, GoalType::GoldMedal)),

    ("/Game/Environments/THPS2/NYC/Goals/Data/nyc_score_high.nyc_score_high", (1, 3, 0, GoalType::Normal)),
    ("/Game/Environments/THPS2/NYC/Goals/Data/nyc_score_pro.nyc_score_pro", (1, 3, 1, GoalType::Normal)),
    ("/Game/Environments/THPS2/NYC/Goals/Data/nyc_score_sick.nyc_score_sick", (1, 3, 2, GoalType::Normal)),
    ("/Game/Environments/THPS2/NYC/Goals/Data/nyc_score_combo.nyc_score_combo", (1, 3, 3, GoalType::Normal)),
    ("/Game/Environments/THPS2/NYC/Goals/Data/nyc_collect_SKATE.nyc_collect_SKATE", (1, 3, 4, GoalType::Normal)),
    ("/Game/Environments/THPS2/NYC/Goals/Data/nyc_collect_5_items.nyc_collect_5_items", (1, 3, 5, GoalType::Normal)),
    ("/Game/Environments/THPS2/NYC/Goals/Data/nyc_env_hydrants.nyc_env_hydrants", (1, 3, 6, GoalType::Normal)),
    ("/Game/Environments/THPS2/NYC/Goals/Data/nyc_gap_grindrails.nyc_gap_grindrails", (1, 3, 7, GoalType::Normal)),
    ("/Game/Environments/THPS2/NYC/Goals/Data/nyc_gap_joeys.nyc_gap_joeys", (1, 3, 8, GoalType::Normal)),
    ("/Game/Environments/THPS2/NYC/Goals/Data/nyc_collect_secret_tape.nyc_collect_secret_tape", (1, 3, 9, GoalType::Normal)),

    ("/Game/Environments/THPS2/Venice/Goals/data/venice_score_high.venice_score_high", (1, 4, 0, GoalType::Normal)),
    ("/Game/Environments/THPS2/Venice/Goals/data/venice_score_pro.venice_score_pro", (1, 4, 1, GoalType::Normal)),
    ("/Game/Environments/THPS2/Venice/Goals/data/venice_score_sick.venice_score_sick", (1, 4, 2, GoalType::Normal)),
    ("/Game/Environments/THPS2/Venice/Goals/data/venice_score_combo.venice_score_combo", (1, 4, 3, GoalType::Normal)),
    ("/Game/Environments/THPS2/Venice/Goals/data/venice_collect_SKATE.venice_collect_SKATE", (1, 4, 4, GoalType::Normal)),
    ("/Game/Environments/THPS2/Venice/Goals/data/venice_collect_5_items.venice_collect_5_items", (1, 4, 5, GoalType::Normal)),
    ("/Game/Environments/THPS2/Venice/Goals/data/venice_env_bum.venice_env_bum", (1, 4, 6, GoalType::Normal)),
    ("/Game/Environments/THPS2/Venice/Goals/data/venice_gap_vb.venice_gap_vb", (1, 4, 7, GoalType::Normal)),
    ("/Game/Environments/THPS2/Venice/Goals/data/venice_gap_tailslide.venice_gap_tailslide", (1, 4, 8, GoalType::Normal)),
    ("/Game/Environments/THPS2/Venice/Goals/data/venice_collect_secret_tape.venice_collect_secret_tape", (1, 4, 9, GoalType::Normal)),

    ("/Game/Environments/THPS2/Street/Goals/Data/street_medal_bronze.street_medal_bronze", (1, 5, 0, GoalType::Medal)),
    ("/Game/Environments/THPS2/Street/Goals/Data/street_medal_silver.street_medal_silver", (1, 5, 1, GoalType::Medal)),
    ("/Game/Environments/THPS2/Street/Goals/Data/street_medal_gold.street_medal_gold", (1, 5, 2, GoalType::GoldMedal)),

    ("/Game/Environments/THPS2/Philly/Goals/Data/philly_score_high.philly_score_high", (1, 6, 0, GoalType::Normal)),
    ("/Game/Environments/THPS2/Philly/Goals/Data/philly_score_pro.philly_score_pro", (1, 6, 1, GoalType::Normal)),
    ("/Game/Environments/THPS2/Philly/Goals/Data/philly_score_sick.philly_score_sick", (1, 6, 2, GoalType::Normal)),
    ("/Game/Environments/THPS2/Philly/Goals/Data/philly_score_combo.philly_score_combo", (1, 6, 3, GoalType::Normal)),
    ("/Game/Environments/THPS2/Philly/Goals/Data/philly_collect_SKATE.philly_collect_SKATE", (1, 6, 4, GoalType::Normal)),
    ("/Game/Environments/THPS2/Philly/Goals/Data/philly_collect_5_items.philly_collect_5_items", (1, 6, 5, GoalType::Normal)),
    ("/Game/Environments/THPS2/Philly/Goals/Data/philly_env_valves.philly_env_valves", (1, 6, 6, GoalType::Normal)),
    ("/Game/Environments/THPS2/Philly/Goals/Data/philly_goal_bluntside.philly_goal_bluntside", (1, 6, 7, GoalType::Normal)),
    ("/Game/Environments/THPS2/Philly/Goals/Data/philly_goal_liptrick.philly_goal_liptrick", (1, 6, 8, GoalType::Normal)),
    ("/Game/Environments/THPS2/Philly/Goals/Data/philly_collect_secret_tape.philly_collect_secret_tape", (1, 6, 9, GoalType::Normal)),

    ("/Game/Environments/THPS2/Bullring/Goals/Data/bullring_medal_bronze.bullring_medal_bronze", (1, 7, 0, GoalType::Medal)),
    ("/Game/Environments/THPS2/Bullring/Goals/Data/bullring_medal_silver.bullring_medal_silver", (1, 7, 1, GoalType::Medal)),
    ("/Game/Environments/THPS2/Bullring/Goals/Data/bullring_medal_gold.bullring_medal_gold", (1, 7, 2, GoalType::GoldMedal)),

    // THPS3
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_score_high.foundry_score_high", (2, 0, 0, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_score_pro.foundry_score_pro", (2, 0, 1, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_score_sick.foundry_score_sick", (2, 0, 2, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_score_combo.foundry_score_combo", (2, 0, 3, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_collect_SKATE.foundry_collect_SKATE", (2, 0, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_collect_SKATE_Set2.foundry_collect_SKATE_Set2", (2, 0, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_collect_SKATE_Set3.foundry_collect_SKATE_Set3", (2, 0, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_Street_TCRail.foundry_Street_TCRail", (2, 0, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_Vert_OverThePipe.foundry_Vert_OverThePipe", (2, 0, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_Park_GeneratorJump.foundry_Park_GeneratorJump", (2, 0, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_SoakTheForeman.foundry_SoakTheForeman", (2, 0, 6, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_GrindMoltenBucket.foundry_GrindMoltenBucket", (2, 0, 7, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_grind_valves.foundry_grind_valves", (2, 0, 8, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_collect_secret_tape.foundry_collect_secret_tape", (2, 0, 9, GoalType::Normal)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_score_legendary.foundry_score_legendary", (2, 0, 10, GoalType::Pro)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_collect_COMBO.foundry_collect_COMBO", (2, 0, 11, GoalType::Pro)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_trick_StompThePresses.foundry_trick_StompThePresses", (2, 0, 12, GoalType::Pro)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_trick_HelixRoom.foundry_trick_HelixRoom", (2, 0, 13, GoalType::Pro)),
    ("/Game/Environments/THPS3/Foundry/Goals/Data/foundry_collect_ForgedTonys.foundry_collect_ForgedTonys", (2, 0, 14, GoalType::Pro)),

    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_score_high.canada_score_high", (2, 1, 0, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_score_pro.canada_score_pro", (2, 1, 1, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_score_sick.canada_score_sick", (2, 1, 2, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_score_combo.canada_score_combo", (2, 1, 3, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_collect_SKATE.canada_collect_SKATE", (2, 1, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_collect_SKATE_2.canada_collect_SKATE", (2, 1, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_collect_SKATE_3.canada_collect_SKATE", (2, 1, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_Street_AroundTheHorn.canada_Street_AroundTheHorn", (2, 1, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_Vert_OverTheBlade.canada_Vert_OverTheBlade", (2, 1, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_Park_ManualTransmission.canada_Park_ManualTransmission", (2, 1, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_GetChuckUnstuck.canada_GetChuckUnstuck", (2, 1, 6, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_BuryThatBully.canada_BuryThatBully", (2, 1, 7, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_ImpressTheSkaters.canada_ImpressTheSkaters", (2, 1, 8, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_collect_secret_tape.canada_collect_secret_tape", (2, 1, 9, GoalType::Normal)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_score_legendary.canada_score_legendary", (2, 1, 10, GoalType::Pro)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_collect_COMBO.canada_collect_COMBO", (2, 1, 11, GoalType::Pro)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_trick_MandatoryVideogameMineCartRide.canada_trick_MandatoryVideogameMineCartRide", (2, 1, 12, GoalType::Pro)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_trick_YoureOverTheHill.canada_trick_YoureOverTheHill", (2, 1, 13, GoalType::Pro)),
    ("/Game/Environments/THPS3/Canada/Goals/Data/canada_collect_HydratePeter.canada_collect_HydratePeter", (2, 1, 14, GoalType::Pro)),

    ("/Game/Environments/THPS3/Rio/Goals/Data/rio_medal_bronze.rio_medal_bronze", (2, 2, 0, GoalType::Medal)),
    ("/Game/Environments/THPS3/Rio/Goals/Data/rio_medal_silver.rio_medal_silver", (2, 2, 1, GoalType::Medal)),
    ("/Game/Environments/THPS3/Rio/Goals/Data/rio_medal_gold.rio_medal_gold", (2, 2, 2, GoalType::GoldMedal)),
    ("/Game/Environments/THPS3/Rio/Goals/Data/rio_platinum_goal_nested.rio_platinum_goal_nested", (2, 2, 3, GoalType::Pro)),

    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_score_high.suburbia_score_high", (2, 3, 0, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_score_pro.suburbia_score_pro", (2, 3, 1, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_score_sick.suburbia_score_sick", (2, 3, 2, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_score_combo.suburbia_score_combo", (2, 3, 3, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_collect_SKATE.suburbia_collect_SKATE", (2, 3, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_collect_SKATE_2.suburbia_collect_SKATE", (2, 3, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_collect_SKATE_3.suburbia_collect_SKATE", (2, 3, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_Street_TrailerHop.suburbia_Street_TrailerHop", (2, 3, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_Vert_BetweenRamps.suburbia_Vert_BetweenRamps", (2, 3, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_Park_Chainlinkgap.suburbia_Park_Chainlinkgap", (2, 3, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_collect_HelpThinMan.suburbia_collect_HelpThinMan", (2, 3, 6, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_collect_RestorePower.suburbia_collect_RestorePower", (2, 3, 7, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_collect_Squash5Pumpkins.suburbia_collect_Squash5Pumpkins", (2, 3, 8, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_collect_secret_tape.suburbia_collect_secret_tape", (2, 3, 9, GoalType::Normal)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_score_legendary.suburbia_score_legendary", (2, 3, 10, GoalType::Pro)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_collect_COMBO.suburbia_collect_COMBO", (2, 3, 11, GoalType::Pro)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_trick_ManualTheSac.suburbia_trick_ManualTheSac", (2, 3, 12, GoalType::Pro)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_trick_TheAbyss.suburbia_trick_TheAbyss", (2, 3, 13, GoalType::Pro)),
    ("/Game/Environments/THPS3/Suburbia/Goals/Data/suburbia_ImpressTheSkaters.suburbia_ImpressTheSkaters", (2, 3, 14, GoalType::Pro)),
    
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_score_high.airport_score_high", (2, 4, 0, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_score_pro.airport_score_pro", (2, 4, 1, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_score_sick.airport_score_sick", (2, 4, 2, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_score_combo.airport_score_combo", (2, 4, 3, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_collect_SKATE.airport_collect_SKATE", (2, 4, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_collect_SKATE_2.airport_collect_SKATE", (2, 4, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_collect_SKATE_3.airport_collect_SKATE", (2, 4, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_trick_AroundBaggage.airport_trick_AroundBaggage", (2, 4, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_trick_OverEscalator.airport_trick_OverEscalator", (2, 4, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_trick_Mulin.airport_trick_Mulin", (2, 4, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_collect_Visit10Countries.airport_collect_Visit10Countries", (2, 4, 6, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_collect_GetTickets.airport_collect_GetTickets", (2, 4, 7, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_collect_StopPickpockets.airport_collect_StopPickpockets", (2, 4, 8, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_collect_secret_tape.airport_collect_secret_tape", (2, 4, 9, GoalType::Normal)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_score_legendary.airport_score_legendary", (2, 4, 10, GoalType::Pro)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_collect_COMBO.airport_collect_COMBO", (2, 4, 11, GoalType::Pro)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_trick_StartToFinish.airport_trick_StartToFinish", (2, 4, 12, GoalType::Pro)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_trick_GateTransfer.airport_trick_GateTransfer", (2, 4, 13, GoalType::Pro)),
    ("/Game/Environments/THPS3/Airport/Goals/Data/airport_collect_Passports.airport_collect_Passports", (2, 4, 14, GoalType::Pro)),

    ("/Game/Environments/THPS3/SkaterIsland/Goals/Data/skaterisland_medal_bronze.skaterisland_medal_bronze", (2, 5, 0, GoalType::Medal)),
    ("/Game/Environments/THPS3/SkaterIsland/Goals/Data/skaterisland_medal_silver.skaterisland_medal_silver", (2, 5, 1, GoalType::Medal)),
    ("/Game/Environments/THPS3/SkaterIsland/Goals/Data/skaterisland_medal_gold.skaterisland_medal_gold", (2, 5, 2, GoalType::GoldMedal)),
    ("/Game/Environments/THPS3/SkaterIsland/Goals/Data/skaterisland_platinum_goal_nested.skaterisland_platinum_goal_nested", (2, 5, 3, GoalType::Pro)),

    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_score_high.LosAngeles_score_high", (2, 6, 0, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_score_pro.LosAngeles_score_pro", (2, 6, 1, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_score_sick.LosAngeles_score_sick", (2, 6, 2, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_score_combo.LosAngeles_score_combo", (2, 6, 3, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_collect_SKATE.LosAngeles_collect_SKATE", (2, 6, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_collect_SKATE_2.LosAngeles_collect_SKATE", (2, 6, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_collect_SKATE_3.LosAngeles_collect_SKATE", (2, 6, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_Street_TowerRailsGap.LosAngeles_Street_TowerRailsGap", (2, 6, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_Vert_TowerPoppinTransfer.LosAngeles_Vert_TowerPoppinTransfer", (2, 6, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_Park_OverTheYellowStoneShack.LosAngeles_Park_OverTheYellowStoneShack", (2, 6, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_FreeBallin.LosAngeles_FreeBallin", (2, 6, 6, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_StartTheEarthquake.LosAngeles_StartTheEarthquake", (2, 6, 7, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_StopTheCarChase.LosAngeles_StopTheCarChase", (2, 6, 8, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_collect_secret_tape.LosAngeles_collect_secret_tape", (2, 6, 9, GoalType::Normal)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_score_legendary.LosAngeles_score_legendary", (2, 6, 10, GoalType::Pro)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_collect_COMBO.LosAngeles_collect_COMBO", (2, 6, 11, GoalType::Pro)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_trick_WireRidin.LosAngeles_trick_WireRidin", (2, 6, 12, GoalType::Pro)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_trick_PassinGas.LosAngeles_trick_PassinGas", (2, 6, 13, GoalType::Pro)),
    ("/Game/Environments/THPS3/LosAngeles/Goals/Data/LosAngeles_BotherBirds.LosAngeles_BotherBirds", (2, 6, 14, GoalType::Pro)),

    ("/Game/Environments/THPS3/Tokyo/Goals/Data/tokyo_medal_bronze.tokyo_medal_bronze", (2, 7, 0, GoalType::Medal)),
    ("/Game/Environments/THPS3/Tokyo/Goals/Data/tokyo_medal_silver.tokyo_medal_silver", (2, 7, 1, GoalType::Medal)),
    ("/Game/Environments/THPS3/Tokyo/Goals/Data/tokyo_medal_gold.tokyo_medal_gold", (2, 7, 2, GoalType::GoldMedal)),
    ("/Game/Environments/THPS3/Tokyo/Goals/Data/tokyo_platinum_goal_nested.tokyo_platinum_goal_nested", (2, 7, 3, GoalType::Pro)),

    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_score_high.cruiseship_score_high", (2, 8, 0, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_score_pro.cruiseship_score_pro", (2, 8, 1, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_score_sick.cruiseship_score_sick", (2, 8, 2, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_score_combo.cruiseship_score_combo", (2, 8, 3, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_collect_SKATE.cruiseship_collect_SKATE", (2, 8, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_collect_SKATE_2.cruiseship_collect_SKATE", (2, 8, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_collect_SKATE_3.cruiseship_collect_SKATE", (2, 8, 4, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_ImpressThePros.cruiseship_ImpressThePros", (2, 8, 5, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_Street_NosebluntSlideAnAwning.cruiseship_Street_NosebluntSlideAnAwning", (2, 8, 6, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_Vert_InvertTheHighWires.cruiseship_Vert_InvertTheHighWires", (2, 8, 6, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_Park_540SalFlipOverPlanter.cruiseship_Park_540SalFlipOverPlanter", (2, 8, 6, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_RaiseTheFerry.cruiseship_RaiseTheFerry", (2, 8, 7, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_TrashTheMuseum.cruiseship_TrashTheMuseum", (2, 8, 8, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_collect_secret_tape.cruiseship_collect_secret_tape", (2, 8, 9, GoalType::Normal)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_score_legendary.cruiseship_score_legendary", (2, 8, 10, GoalType::Pro)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_collect_COMBO.cruiseship_collect_COMBO", (2, 8, 11, GoalType::Pro)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_trick_CrazyLifeboatTransfer.cruiseship_trick_CrazyLifeboatTransfer", (2, 8, 12, GoalType::Pro)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_trick_AAAAAEEE.cruiseship_trick_AAAAAEEE", (2, 8, 13, GoalType::Pro)),
    ("/Game/Environments/THPS3/CruiseShip/Goals/Data/cruiseship_EnergyDrinks.cruiseship_EnergyDrinks", (2, 8, 14, GoalType::Pro)),

    // THPS4

    ("/Game/Environments/THPS4/College/Goals/Data/college_score_high.college_score_high", (3, 0, 0, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_score_combo.college_score_combo", (3, 0, 1, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_score_pro.college_score_pro", (3, 0, 2, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_score_sick.college_score_sick", (3, 0, 3, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_collect_SKATE.college_collect_SKATE", (3, 0, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_collect_SKATE_set2.college_collect_SKATE_set2", (3, 0, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_collect_SKATE_set3.college_collect_SKATE_set3", (3, 0, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_trick_Fountain_Street.college_trick_Fountain_Street", (3, 0, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_trick_Tennis_Vert.college_trick_Tennis_Vert", (3, 0, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_trick_BannerLip_Park.college_trick_BannerLip_Park", (3, 0, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_GetBackAtTheFrat.college_GetBackAtTheFrat", (3, 0, 6, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_StopTheCar.college_StopTheCar", (3, 0, 7, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_OfficerTomsBanners.college_OfficerTomsBanners", (3, 0, 8, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_collect_secret_tape.college_collect_secret_tape", (3, 0, 9, GoalType::Normal)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_score_legendary.college_score_legendary", (3, 0, 10, GoalType::Pro)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_collect_COMBO.college_collect_COMBO", (3, 0, 11, GoalType::Pro)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_FindPinkElephants.college_FindPinkElephants", (3, 0, 12, GoalType::Pro)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_ImpressTheSkaters.college_ImpressTheSkaters", (3, 0, 13, GoalType::Pro)),
    ("/Game/Environments/THPS4/College/Goals/Data/college_Float_Gap.college_Float_Gap", (3, 0, 14, GoalType::Pro)),

    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_score_high.sanfrancisco_score_high", (3, 1, 0, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_score_pro.sanfrancisco_score_pro", (3, 1, 1, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_score_sick.sanfrancisco_score_sick", (3, 1, 2, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_score_combo.sanfrancisco_score_combo", (3, 1, 3, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_collect_SKATE.sanfrancisco_collect_SKATE", (3, 1, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_collect_SKATE_Set2.sanfrancisco_collect_SKATE_Set2", (3, 1, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_collect_SKATE_Set3.sanfrancisco_collect_SKATE_Set3", (3, 1, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_Street_WatersideRailing.sanfrancisco_Street_WatersideRailing", (3, 1, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_Vert_PierSign.sanfrancisco_Vert_PierSign", (3, 1, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_Park_OverTheStreet.sanfrancisco_Park_OverTheStreet", (3, 1, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_collect_5MissingPackages.sanfrancisco_collect_5MissingPackages", (3, 1, 6, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_trick_OverheadWalkway.sanfrancisco_trick_OverheadWalkway", (3, 1, 7, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_SavePainterNeal.sanfrancisco_SavePainterNeal", (3, 1, 8, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_collect_secret_tape.sanfrancisco_collect_secret_tape", (3, 1, 9, GoalType::Normal)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_score_legendary.sanfrancisco_score_legendary", (3, 1, 10, GoalType::Pro)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_collect_COMBO.sanfrancisco_collect_COMBO", (3, 1, 11, GoalType::Pro)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_trick_Setup.sanfrancisco_trick_Setup", (3, 1, 12, GoalType::Pro)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_StolenCamera.sanfrancisco_StolenCamera", (3, 1, 13, GoalType::Pro)),
    ("/Game/Environments/THPS4/SanFrancisco/Goals/Data/sanfrancisco_RudeDudes.sanfrancisco_RudeDudes", (3, 1, 14, GoalType::Pro)),

    ("/Game/Environments/THPSIG/MovieStudio/Goals/Data/moviestudio_medal_bronze.moviestudio_medal_bronze", (3, 2, 0, GoalType::Medal)),
    ("/Game/Environments/THPSIG/MovieStudio/Goals/Data/moviestudio_medal_silver.moviestudio_medal_silver", (3, 2, 1, GoalType::Medal)),
    ("/Game/Environments/THPSIG/MovieStudio/Goals/Data/moviestudio_medal_gold.moviestudio_medal_gold", (3, 2, 2, GoalType::GoldMedal)),
    ("/Game/Environments/THPSIG/MovieStudio/Goals/Data/moviestudio_platinum_goal_nested.moviestudio_platinum_goal_nested", (3, 2, 3, GoalType::Pro)),

    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_score_high.alcatraz_score_high", (3, 3, 0, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_score_pro.alcatraz_score_pro", (3, 3, 1, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_score_sick.alcatraz_score_sick", (3, 3, 2, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_score_combo.alcatraz_score_combo", (3, 3, 3, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_collect_SKATE.alcatraz_collect_SKATE", (3, 3, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_collect_SKATE2.alcatraz_collect_SKATE2", (3, 3, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_collect_SKATE3.alcatraz_collect_SKATE3", (3, 3, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_Street_GrindFogHorn.alcatraz_Street_GrindFogHorn", (3, 3, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_Vert_AcrossThePipes.alcatraz_Vert_AcrossThePipes", (3, 3, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_Park_OverCrumbledWall.alcatraz_Park_OverCrumbledWall", (3, 3, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_PhotobombTourists.alcatraz_PhotobombTourists", (3, 3, 6, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_SpineIntoWaterTower.alcatraz_SpineIntoWaterTower", (3, 3, 7, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_FindCellblockKeys.alcatraz_FindCellblockKeys", (3, 3, 8, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_collect_secret_tape.alcatraz_collect_secret_tape", (3, 3, 9, GoalType::Normal)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_score_legendary.alcatraz_score_legendary", (3, 3, 10, GoalType::Pro)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_collect_COMBO.alcatraz_collect_COMBO", (3, 3, 11, GoalType::Pro)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_trick_off_bulldozer.alcatraz_trick_off_bulldozer", (3, 3, 12, GoalType::Pro)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_massive_crumbling_stairset.alcatraz_massive_crumbling_stairset", (3, 3, 13, GoalType::Pro)),
    ("/Game/Environments/THPS4/Alcatraz/Goals/Data/alcatraz_take_the_tour.alcatraz_take_the_tour", (3, 3, 14, GoalType::Pro)),

    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_score_high.waterpark_score_high", (3, 4, 0, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_score_pro.waterpark_score_pro", (3, 4, 1, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_score_sick.waterpark_score_sick", (3, 4, 2, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_score_combo.waterpark_score_combo", (3, 4, 3, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_collect_SKATE.waterpark_collect_SKATE", (3, 4, 4, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_collect_SKATE2.waterpark_collect_SKATE2", (3, 4, 4, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_collect_SKATE3.waterpark_collect_SKATE3", (3, 4, 4, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_style_street_goal.waterpark_style_street_goal", (3, 4, 5, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_style_vert_goal.waterpark_style_vert_goal", (3, 4, 5, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_style_park_goal.waterpark_style_park_goal", (3, 4, 5, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_smash_the_mascots.waterpark_smash_the_mascots", (3, 4, 6, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_drain_pirates_bay.waterpark_drain_pirates_bay", (3, 4, 7, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_restore_arcade_power.waterpark_restore_arcade_power", (3, 4, 8, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_collect_secret_tape.waterpark_collect_secret_tape", (3, 4, 9, GoalType::Normal)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_score_legendary.waterpark_score_legendary", (3, 4, 10, GoalType::Pro)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_collect_COMBO.waterpark_collect_COMBO", (3, 4, 11, GoalType::Pro)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_ImpressGoal.waterpark_ImpressGoal", (3, 4, 12, GoalType::Pro)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_collect_arcade_tokens.waterpark_collect_arcade_tokens", (3, 4, 13, GoalType::Pro)),
    ("/Game/Environments/THPSIG/WaterPark/Goals/Data/waterpark_dunk_bucket.waterpark_dunk_bucket", (3, 4, 14, GoalType::Pro)),

    ("/Game/Environments/THPS4/Kona/Goals/Data/kona_medal_bronze.kona_medal_bronze", (3, 5, 0, GoalType::Medal)),
    ("/Game/Environments/THPS4/Kona/Goals/Data/kona_medal_silver.kona_medal_silver", (3, 5, 1, GoalType::Medal)),
    ("/Game/Environments/THPS4/Kona/Goals/Data/kona_medal_gold.kona_medal_gold", (3, 5, 2, GoalType::GoldMedal)),
    ("/Game/Environments/THPS4/Kona/Goals/Data/kona_platinum_goal_nested.kona_platinum_goal_nested", (3, 5, 3, GoalType::Pro)),

    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_score_high.shipyard_score_high", (3, 6, 0, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_score_pro.shipyard_score_pro", (3, 6, 1, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_score_sick.shipyard_score_sick", (3, 6, 2, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_score_combo.shipyard_score_combo", (3, 6, 3, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_collect_SKATE.shipyard_collect_SKATE", (3, 6, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_collect_SKATE2.shipyard_collect_SKATE2", (3, 6, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_collect_SKATE3.shipyard_collect_SKATE3", (3, 6, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_style_goal_street.shipyard_style_goal_street", (3, 6, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_style_goal_vert.shipyard_style_goal_vert", (3, 6, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_style_goal_park.shipyard_style_goal_park", (3, 6, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_collect_rivets.shipyard_collect_rivets", (3, 6, 6, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_lunch_delivery.shipyard_lunch_delivery", (3, 6, 7, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_manual_combo_the_train.shipyard_manual_combo_the_train", (3, 6, 8, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_collect_secret_tape.shipyard_collect_secret_tape", (3, 6, 9, GoalType::Normal)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_score_legendary.shipyard_score_legendary", (3, 6, 10, GoalType::Pro)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_collect_COMBO.shipyard_collect_COMBO", (3, 6, 11, GoalType::Pro)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_across_roofs.shipyard_across_roofs", (3, 6, 12, GoalType::Pro)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_into_container.shipyard_into_container", (3, 6, 13, GoalType::Pro)),
    ("/Game/Environments/THPS4/Shipyard/Goals/Data/shipyard_vent_rails.shipyard_vent_rails", (3, 6, 14, GoalType::Pro)),

    ("/Game/Environments/THPS4/London/Goals/Data/london_score_high.london_score_high", (3, 7, 0, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_score_pro.london_score_pro", (3, 7, 1, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_score_sick.london_score_sick", (3, 7, 2, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_score_combo.london_score_combo", (3, 7, 3, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_collect_SKATE.london_collect_SKATE", (3, 7, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_collect_SKATE_Set2.london_collect_SKATE_Set2", (3, 7, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_collect_SKATE_Set3.london_collect_SKATE_Set3", (3, 7, 4, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_Street_Archway.london_Street_Archway", (3, 7, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_Vert_Fountains.london_Vert_Fountains", (3, 7, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_Park_AmericanCar.london_Park_AmericanCar", (3, 7, 5, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_collect_ConstableRichard.london_collect_ConstableRichard", (3, 7, 6, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_collect_Wallride2Buses.london_collect_Wallride2Buses", (3, 7, 7, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_collect_FreeStompy.london_collect_FreeStompy", (3, 7, 8, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_collect_secret_tape.london_collect_secret_tape", (3, 7, 9, GoalType::Normal)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_score_legendary.london_score_legendary", (3, 7, 10, GoalType::Pro)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_collect_COMBO.london_collect_COMBO", (3, 7, 11, GoalType::Pro)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_Gap_SouthbankLights.london_Gap_SouthbankLights", (3, 7, 12, GoalType::Pro)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_collect_ImpressThePros.london_collect_ImpressThePros", (3, 7, 13, GoalType::Pro)),
    ("/Game/Environments/THPS4/London/Goals/Data/london_StompyPlushies.london_StompyPlushies", (3, 7, 14, GoalType::Pro)),

    ("/Game/Environments/THPS4/Zoo/Goals/Data/zoo_medal_bronze.zoo_medal_bronze", (3, 8, 0, GoalType::Medal)),
    ("/Game/Environments/THPS4/Zoo/Goals/Data/zoo_medal_silver.zoo_medal_silver", (3, 8, 1, GoalType::Medal)),
    ("/Game/Environments/THPS4/Zoo/Goals/Data/zoo_medal_gold.zoo_medal_gold", (3, 8, 2, GoalType::GoldMedal)),
    ("/Game/Environments/THPS4/Zoo/Goals/Data/zoo_platinum_goal_nested.zoo_platinum_goal_nested", (3, 8, 3, GoalType::Pro)),

    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_score_high.pinball_score_high", (3, 9, 0, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_score_pro.pinball_score_pro", (3, 9, 1, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_score_sick.pinball_score_sick", (3, 9, 2, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_score_combo.pinball_score_combo", (3, 9, 3, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_collect_SKATE.pinball_collect_SKATE", (3, 9, 4, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_collect_SKATE2.pinball_collect_SKATE2", (3, 9, 4, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_collect_SKATE3.pinball_collect_SKATE3", (3, 9, 4, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_style_street_goal.pinball_style_street_goal", (3, 9, 5, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_style_vert_goal.pinball_style_vert_goal", (3, 9, 5, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_style_park_goal.pinball_style_park_goal", (3, 9, 5, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_tombstones.pinball_tombstones", (3, 9, 6, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_collect_tokens.pinball_collect_tokens", (3, 9, 7, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_birdman_head.pinball_birdman_head", (3, 9, 8, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_collect_secret_tape.pinball_collect_secret_tape", (3, 9, 9, GoalType::Normal)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_score_legendary.pinball_score_legendary", (3, 9, 10, GoalType::Pro)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_collect_COMBO.pinball_collect_COMBO", (3, 9, 11, GoalType::Pro)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_gap_goal_highriserails.pinball_gap_goal_highriserails", (3, 9, 12, GoalType::Pro)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_gap_goal_TrickBall.pinball_gap_goal_TrickBall", (3, 9, 13, GoalType::Pro)),
    ("/Game/Environments/THPSIG/Pinball/Goals/Data/pinball_gap_goal_Flipper_Jump.pinball_gap_goal_Flipper_Jump", (3, 9, 14, GoalType::Pro)),
];